const IMAGES = {
    DOTAEXPERT: { img: require("./thumbnails/dota2expert.png").default, alt: "dota" },
    FREESKINS: { img: require("./thumbnails/freeskins.webp").default, alt: "Free Skins" },
    SWAGBUCKS: { img: require("./thumbnails/swagbucks.png").default, alt: "Swag Bucks" },
    BITSKINS: { img: require("./thumbnails/bitskins.png").default, alt: "BitsSkins" },
    STAKE: { img: require("./thumbnails/stake.png").default, alt: "Stake" },
    CSGOEMPIRE: { img: require("./thumbnails/csgoempire.png").default, alt: "Csgoempire" },
    CSGOPOLYGON: { img: require("./thumbnails/csgopolygon.png").default, alt: "Csgopolygon" },
    CSGO500: { img: require("./thumbnails/csgo500.png").default, alt: "CSGO500" },
    WTFSKINS: { img: require("./thumbnails/wtfskins.png").default, alt: "WTFSKINS" },
    CSGOLIVE: { img: require("./thumbnails/csgolive.png").default, alt: "Csgolive" },
    IDLEEMPIRE: { img: require("./thumbnails/idleempire.png").default, alt: "Idle-empire" },
    HELLCASE: { img: require("./thumbnails/hellcase.png").default, alt: "Hellcase" },
    DATDROP: { img: require("./thumbnails/datdrop.png").default, alt: "datdrop" },
    CSGOATSE: { img: require("./thumbnails/csgoatse.png").default, alt: "csgoatse" },
    ZORGO: { img: require("./thumbnails/zorgogames.png").default, alt: "zorgo" },
    GAMDOM: { img: require("./thumbnails/gamdom.png").default, alt: "Gamdom" },
    CSGOROLL: { img: require("./thumbnails/csgoroll.png").default, alt: "Csgoroll" },
    // GAIN: { img: require("./thumbnails/Gain.png").default, alt: "Gain" },
    CSGOPRIME: { img: require("./thumbnails/csgoprime.png").default, alt: "Csgoprime" },
    GAIN: { img: require("./thumbnails/gain.png").default, alt: "Gain.gg" },
    ROLLBIT: { img: require("./thumbnails/rollbit.svg").default, alt: "Rollbit" },
};

export default IMAGES;
